### ISSUE TITLE
メニューのGitHubアイコンのリンク先が東京都版になっている

### ISSUE THREAD

**Issue by rioil** [air-h-128k-il/covid19#104]
## 起こっている問題 / The Problem
- メニュー下部にあるGitHubアイコンのリンク先が東京都版リポジトリとなっている

## 期待する見せ方・挙動 / Expected Behavior
- 新潟県版にリンク先を変更する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by air-h-128k-il** [comment]
ご指摘ありがとう
直しておきます
