### ISSUE TITLE
Google Analyticsのidを変える

### ISSUE THREAD

**Issue by michiyac4ngt** [air-h-128k-il/covid19#2]
### nuxt.config.tsの修正をお願いします

![image](https://user-images.githubusercontent.com/14312281/76965175-3631c200-6967-11ea-87b2-f391fda3cec5.png)

を各自のGoogle Analyticsのidに変更する(しないと東京都側にアクセスログが飛んでしまうため)

Google Analyticsのidは各自でとってください。

参考　[派生版を作るときにまず、やることリスト](https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg?view#%E6%B4%BE%E7%94%9F%E7%89%88%E3%82%92%E4%BD%9C%E3%82%8B%E3%81%A8%E3%81%8D%E3%81%AB%E3%81%BE%E3%81%9A%E3%80%81%E3%82%84%E3%82%8B%E3%81%93%E3%81%A8%E3%83%AA%E3%82%B9%E3%83%88)

**Comment by air-h-128k-il** [comment]
了解
